@baseUrl = http://localhost:7080/api/v1
@adminUsername = admin1
@adminPassword = admin12
@userUsername = user12
@userPassword = test12


### Create User - this one will only get a USER role by default
POST {{baseUrl}}/auth/register/

{
    "username": "user12",
    "password": "test12"
}

> {% client.global.set("token", response.body.token); %}

### USER login to get a token
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{userUsername}}",
  "password": "{{userPassword}}"
}

> {% client.global.set("token", response.body.token); %}


### Create Admin user
POST {{baseUrl}}/auth/register/

{
    "username": "admin1",
    "password": "admin12"
}

> {% client.global.set("token", response.body.token); %}

### ADMIN login to get a token
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}

> {% client.global.set("token", response.body.token); %}

###  Get allGuides
GET {{baseUrl}}/guides
Authorization: Bearer {{token}}

### Get guideById
GET {{baseUrl}}/guides/1
Authorization: Bearer {{token}}

### Create new guide
POST {{baseUrl}}/trips/guides
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Jonas",
  "email": "jonas@guide.dk",
  "phoneNumber": 12345678,
  "experienceInYears": 5
}

### Update existing guide
PUT {{baseUrl}}/guides/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "experienceInYears": 7
}

### Delete guide
DELETE {{baseUrl}}/guides/1
Authorization: Bearer {{token}}

### Create new trip
POST {{baseUrl}}/trips
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Beach trip",
  "startTime": "2025-11-01T09:00:00",
  "endTime": "2025-11-01T17:00:00",
  "locationCordinates": "57.048",
  "price": 5000,
  "category": "BEACH"
}

### Update trip
PUT {{baseUrl}}/trips/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "price": 7000
}

### Add Guide to Trip
PUT {{baseUrl}}/trips/1/guides/1
Authorization: Bearer {{token}}

### Get all trips
GET {{baseUrl}}/trips
Authorization: Bearer {{token}}

### Get trips by category
GET {{baseUrl}}/trips?category=BEACH
Authorization: Bearer {{token}}

### Get trip by id
GET {{baseUrl}}/trips/1
Authorization: Bearer {{token}}

### Get trip by id and packing list by trip Category (same as above just added feature)
GET {{baseUrl}}/trips/1
Authorization: Bearer {{token}}

### Delete trip
DELETE {{baseUrl}}/trips/1
Authorization: Bearer {{token}}

### Get total price Guide by Trips
GET {{baseUrl}}/trips/guides/totalprice
Authorization: Bearer {{token}}

### Get packing weight
GET {{baseUrl}}/trips/1/packing/weight
Authorization: Bearer {{token}}